version: "3.1"

services:
  api-server:
    build: .
    ports:
      - 9090:9090
    # network_mode: "host"
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  api-documentation:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - 9080:9080

  tzkt-indexer:
    container_name: tzkt-sync
    restart: always
    image: bakingbad/tzkt-sync:latest
    # network_mode: "host"
    environment:
      ConnectionStrings__DefaultConnection: host=172.23.0.2;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt_admin};password=${POSTGRES_PASSWORD:-tzkt_admin}; 
      TezosNode__Endpoint: https://mainnet-tezos.giganode.io/
      TezosNode_Timeout: 60
      Logging__LogLevel__Default: "Debug"
