version: "3.1"

services:
  api-server:
    build: .
    ports:
      - 9090:9090
    restart: on-failure
    depends_on:
      - api-db
    deploy:
      restart_policy:
        condition: on-failure

  api-documentation:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - 9080:9080

  api-db:
    image: postgres:13
    restart: always
    volumes:
      - ./databases/scripts:/docker-entrypoint-initdb.d
      - postgres-tzsign:/var/lib/postgresql/data
    environment:
      # POSTGRES_USER: ${POSTGRES_USER:-tzsign}
      POSTGRES_PASSWORD: qwerty
      # POSTGRES_DB: ${POSTGRES_DB:-tzsign_db}
    ports:
      - 127.0.0.1:5433:5432

volumes:
  postgres-tzsign:
